[tool.poetry]
name = "realtime-py"
version = "0.1.2"
description = ""
authors = ["None"]

[tool.poetry.dependencies]
python = "^3.7"
dataclasses = "^0.6"
websockets = "^8.1"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
