[tool.poetry]
name = "realtime"
version = "0.0.4"
description = ""
authors = ["Joel"]

[tool.poetry.dependencies]
python = "^3.7"
websockets = "^10.3"
python-dateutil = "^2.8.1"
typing-extensions = "^4.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
